---
# tasks file for ansible-vscodium-installer

- name: "{{ ansible_os_family }} OS family installation"
  include_tasks: "{{ ansible_os_family }}.yml"

# Common tasks for configuration

- name: "Check existance of path: {{ unix_vscodium_user_config }}"
  ansible.builtin.file:
    path: "{{ unix_vscodium_user_config }}"
    state: directory
    mode: '0700'

- name: Add Microsoft VSCode extension marketplace
  when: vscode_marketplace
  ansible.builtin.template:
    src: vscode_marketplace_product.json.j2
    dest: "{{ unix_vscodium_user_config }}/product.json"
    mode: '0644'

- name: Install extensions
  when: vscodium_extensions | length > 0
  with_items: "{{ vscodium_extensions }}"
  ansible.builtin.command:
    cmd: "codium --install-extension {{ item }}"
  register: vscode_extensions
  changed_when: "'already installed' not in vscode_extensions.stdout"

- name: Add custom user settings
  ansible.builtin.copy:
    src: "{{ vscodium_settings }}"
    dest: "{{ unix_vscodium_user_config }}/settings.json"
    mode: '0644'
  when: vscodium_settings

- name: Add custom user keybindings
  ansible.builtin.copy:
    src: "{{ vscodium_keybindings }}"
    dest: "{{ unix_vscodium_user_config }}/keybindings.json"
    mode: '0644'
  when: vscodium_keybindings

- name: Add custom user tasks
  ansible.builtin.copy:
    src: "{{ vscodium_tasks }}"
    dest: "{{ unix_vscodium_user_config }}/tasks.json"
    mode: '0644'
  when: vscodium_tasks
