---
# tasks file for ansible-vscodium-installer

- name: RedHat OS family installation
  when: ansible_os_family == 'RedHat'
  #become: true
  block:

    - name: Import VSCodium gpg key to rpm db
      ansible.builtin.rpm_key:
        key: "{{ vscodium_gpg_key }}"
        fingerprint: "{{ vscodium_gpg_key_fingerprint }}"

    - name: Add repository
      ansible.builtin.yum_repository:
        name: gitlab.com_paulcarroty_vscodium_repo
        description: VSCodium repository created by Ansible
        baseurl: "{{ vscodium_rpm_repo_baseurl }}"
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: "{{ vscodium_gpg_key }}"
        metadata_expire: 3600

    - name: Install VSCodium
      ansible.builtin.dnf:
        name: codium
        state: present

- name: Debian OS family installation
  when: ansible_os_family == 'Debian'
  #become: true
  block:

    - name: Import VSCodium gpg key to keyring
      ansible.builtin.apt_key:
        url: "{{ vscodium_gpg_key }}"
        id: "{{ vscodium_gpg_key_fingerprint | regex_replace('\\s', '') }}"
        state: present

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "deb {{ vscodium_deb_repo_baseurl }} vscodium main"
        filename: vscodium
        update_cache: true
        state: present

    - name: Install VSCodium
      ansible.builtin.apt:
        name: codium
        update_cache: true

- name: "Check existance of path: {{ unix_vscodium_user_config }}"
  ansible.builtin.file:
    path: "{{ unix_vscodium_user_config }}"
    state: directory
    mode: '0700'

- name: Add Microsoft VSCode extension marketplace
  when: vscode_marketplace
  ansible.builtin.template:
    src: vscode_marketplace_product.json.j2
    dest: "{{ unix_vscodium_user_config }}/product.json"
    mode: '0644'

- name: Install extensions
  when: vscodium_extensions | length > 0
  with_items: "{{ vscodium_extensions }}"
  ansible.builtin.command:
    cmd: "codium --install-extension {{ item }}"
  register: vscode_extensions
  changed_when: "'already installed' not in vscode_extensions.stdout"

- name: Add custom user settings
  ansible.builtin.copy:
    src: "{{ vscodium_settings }}"
    dest: "{{ unix_vscodium_user_config }}/settings.json"
    mode: '0644'
  when: vscodium_settings

- name: Add custom user keybindings
  ansible.builtin.copy:
    src: "{{ vscodium_keybindings }}"
    dest: "{{ unix_vscodium_user_config }}/keybindings.json"
    mode: '0644'
  when: vscodium_keybindings

- name: Add custom user tasks
  ansible.builtin.copy:
    src: "{{ vscodium_tasks }}"
    dest: "{{ unix_vscodium_user_config }}/tasks.json"
    mode: '0644'
  when: vscodium_tasks
