---
- name: Prepare playbook
  hosts: all
  gather_facts: false

  tasks:
    - name: Install goodies (python3 & pip) for Debian OS-Family distros
      ansible.builtin.raw: grep -q "debian" /etc/*-release && apt-get update && apt-get install -y python3 python3-pip
      args:
        executable: /bin/bash
      register: result
      failed_when:
        - result.rc != 0
        - result.stderr != ""
      changed_when: result.rc == 0

    - name: Install sudo & gpg
      ansible.builtin.package:
        name:
          - sudo
          - gpg
        state: present
